FROM node:14-alpine

WORKDIR /usr/src/app

COPY package*.json ./

RUN yarn

COPY . .

RUN yarn build

RUN yarn typeorm migration:run

RUN yarn seed:run

RUN rm -rf ./src

EXPOSE 3333

CMD ["yarn", "start"]
