version: '3.7'

services:
  database:
    image: postgres
    container_name: jobfinder-db
    restart: always
    ports:
      - '${POSTGRES_PORT_EXTERNAL}:${POSTGRES_PORT}'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_PORT_EXTERNAL=${POSTGRES_PORT_EXTERNAL}

    volumes:
      - pgdata:/data/postgres
    env_file:
      - .env
  app:
    build: .
    container_name: jobfinder-api
    restart: always
    ports:
      - '${API_PORT_EXTERNAL}:${API_PORT}'
    environment:
      - API_PORT=${API_PORT}
      - API_PORT_EXTERNAL=${API_PORT_EXTERNAL}
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local
